# Generated by Django 2.0.4 on 2018-04-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
